name: Add Update Label to Issues Weekly

on: workflow_dispatch

jobs:
  Add-Update-Label-to-Issues-Weekly:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/github-script@v4
        env:
          READY_FOR_TEST_COLUMN_ID: ${{ secrets.READY_FOR_TEST_COLUMN_ID }}
        with:
          script: |
            const { READY_FOR_TEST_COLUMN_ID } = process.env;
            const script = require('./github-actions/add-update-label-weekly/add-label.js');
            script({ g: github, c: context }, READY_FOR_TEST_COLUMN_ID);
