name: Add Update Label to Issues Weekly

on: 
  workflow_dispatch:
jobs:
  Add-Update-Label-to-Issues-Weekly:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/github-script@v4
        env:
          ICE_BOX: ${{ secrets.ICE_BOX }}
        with:
          script: |
            const { ICE_BOX } = process.env;
            const script = require('./github-actions/add-update-label-weekly/add-label.js');
            script({ g: github, c: context }, ICE_BOX);
