# TODO
// TODO

# TOYAMLDO
// TOYAMLDO

# FUTUREBUG
// FUTUREBUG

# /[a-z]+/g;
// /[a-z]+/g;
/[a-z]+/g;

# 2001-12-15T02:59:43.1Z
// 2001-12-15T02:59:43.1Z
2001-12-15T02:59:43.1Z

`tag:yaml.org,2002:<t>`.
