# TODO
// TODO

# TOYAMLDO

# FUTUREBUG
// FUTUREBUG

# /[a-z]+/g;
// /[a-z]+/g;
/[a-z]+/g;

# 2001-12-15T02:59:43.1Z
// 2001-12-15T02:59:43.1Z
2001-12-15T02:59:43.1Z
- 2001-12-15T02:59:43.1Z
"2001-12-15T02:59:43.1Z"

`tag:yaml.org,2002:<t>`.


- "name": "Jim Knopf"
  address: {
    "street":,
    "number": -1,
    "country": "Lummerland"
  }
- name: Frau Mahlzahn
  address:
    street: |
        Alte Strasse
    number: 133
    country: <
        Kummerland
- !include external.yml

"unterminated string

42


- &A { x: 23, y: 42 }
- x: 56
  <<: *A
